"""Corrección de longitud VARCHAR

Revision ID: 9eaeae80292e
Revises: 
Create Date: 2024-11-03 21:27:02.011452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9eaeae80292e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gastos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('metas_ahorro', 'fecha_limite',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=230),
               existing_nullable=True)
    op.alter_column('metas_ahorro', 'estado',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'En progreso'"))
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'hashed_password')
    op.alter_column('metas_ahorro', 'estado',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'En progreso'"))
    op.alter_column('metas_ahorro', 'fecha_limite',
               existing_type=sa.String(length=230),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('gastos', 'descripcion',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
